const Enmap = require('enmap');

const userTable = new Enmap({
    name: 'UserManager',
    fetchAll: false,
    autoFetch: true,
    cloneLevel: 'deep'
});

const canvasData = new Enmap({
    name: 'EditAvatarTable',
    fetchAll: false,
    autoFetch: true,
    cloneLevel: 'deep',
    dataDir: './data/canvasData',
    autoEnsure: {
        'edit-avatar': {
            avatarFusion: [],
            eject: [],
            fire: [],
            hat: [],
            hearts: [],
            heLivesInYou: [],
            iHaveThePower: [],
            milk: [],
            rip: [],
            sip: [],
            steamNowPlaying: [],
            steamNowPlayingClassic: [],
            triggered: [],
        },
        'edit-image': [],
        'edit-meme': {
            '3000years': [],
            alert: [],
            bartChalkboard: [],
            beLikeBill: [],
            beautiful: [],
            boardroomMeeting: [],
            challenger: [],
            changeMyMind: [],
            chiIdea: [],
            crush: [],
            cursedSponge: [],
            deepFry: [],
            demotivational: [],
            distractedBF: [],
            drakePosting: [],
            EddFactBook: [],
            enslaved: [],
            FoodBroke: [],
            ForFiveHours: [],
            genieRules: [],
            girlWorthFightingFor: [],
            gruPlan: [],
            iFearNoMan: [],
            ifThoseKidsCouldRead: [],
            kyonGun: [],
            like: [],
            LisaPresentation: [],
            LookAtThisPhotograph: [],
            MarioBrosViews: [],
            memeGenClassic: [],
            memeGenModern: [],
            metamorphosis: [],
            MyCollectionGrows: [],
            newPassword: [],
            nikeAd: [],
            PanikKalmPanik: [],
            PhoebeTeachingJoey: [],
            pills: [],
            PlanktonPlan: [],
            pogchamp: [],
            ScrollOfTruth: [],
            SkyrimSkill: [],
            SonicSays: [],
            soraSelfie: [],
            sos: [],
            SpidermanPointing: [],
            SpongebobBurn: [],
            ThatSignWontStopMe: [],
            ThisGuy: [],
            ToBeContinued: [],
            TuxedoPooh: [],
            TwoButtons: [],
            UltimateTattoo: [],
            VietnamFlashbacks: [],
            WorseThanHitler: [],
            worthless: []
        },
    }
});

module.exports.canvasData = canvasData;
module.exports.userTable = userTable;