const { canvasData } = require('./main');

module.exports = async function initSetup() {
    // If canvasData collection is empty => ensure new keys 
    if ((await canvasData.keys).length === 0) {
        await canvasData.ensure('edit-avatar', {
            avatarFusion: [],
            eject: [],
            fire: [],
            hat: [],
            hearts: [],
            heLivesInYou: [],
            iHaveThePower: [],
            milk: [],
            rip: [],
            sip: [],
            steamNowPlaying: [],
            steamNowPlayingClassic: [],
            triggered: [],
        });
    
        await canvasData.ensure('edit-image', { 
            minecraftachivement: [],
            approve: [],
            axiscult: [],
            blur: [],
            bobross: [],
            brazzers: [],
            caution: [],
            certificate: [],
            chineserestaurant: [],
            circle: [],
            color: [],
            communist: [],
            contrast: [],
            createQr: [],
            customtext: [],
            danger: [],
            dannydevito: [],
            desaturate: [],
            dexter: [],
            distort: [],
            eyes: [],
            fireframe: [],
            gandhiquote: [],
            ghost: [],
            glassshatter: [],
            glitch: [],
            greyscale: [],
            gun: [],
            hands: [],
            highwaysign: [],
            hollywoodstar: [],
            invert: [],
            ifunny: [],
            jeopardyQuestion: [],
            legoIcon: [],
            licensePlate: [],
            mirror: [],
            motionBlur: [],
            newspaper: [],
            pet: [],
            pixelize: [],
            policeTape: [],
            rainbow: [],
            rejected: [],
            rotate: [],
            silouette: [],
            simp: [],
            speedLimit: [],
            SpongebobTimeCard: [],
            spotifyNowPlaying: [],
            tint: [],
            wanted: [],
            youDied: [],
            charcoal: [],
            emboss: [],
            fishEye: [],
            liquidRescale: [],
            noise: [],
            oilPainting: [],
            squish: [],
            swirl: [],
            undertale: [],
            wildPokemon: []
        });
    
        await canvasData.ensure('edit-meme', {
            '3000years': [],
            alert: [],
            bartChalkboard: [],
            beLikeBill: [],
            beautiful: [],
            boardroomMeeting: [],
            challenger: [],
            changeMyMind: [],
            chiIdea: [],
            crush: [],
            cursedSponge: [],
            deepFry: [],
            demotivational: [],
            distractedBF: [],
            drakePosting: [],
            EddFactBook: [],
            enslaved: [],
            FoodBroke: [],
            ForFiveHours: [],
            genieRules: [],
            girlWorthFightingFor: [],
            gruPlan: [],
            iFearNoMan: [],
            ifThoseKidsCouldRead: [],
            kyonGun: [],
            like: [],
            LisaPresentation: [],
            LookAtThisPhotograph: [],
            MarioBrosViews: [],
            memeGenClassic: [],
            memeGenModern: [],
            metamorphosis: [],
            MyCollectionGrows: [],
            newPassword: [],
            nikeAd: [],
            PanikKalmPanik: [],
            PhoebeTeachingJoey: [],
            pills: [],
            PlanktonPlan: [],
            pogchamp: [],
            ScrollOfTruth: [],
            SkyrimSkill: [],
            SonicSays: [],
            soraSelfie: [],
            sos: [],
            SpidermanPointing: [],
            SpongebobBurn: [],
            ThatSignWontStopMe: [],
            ThisGuy: [],
            ToBeContinued: [],
            TuxedoPooh: [],
            TwoButtons: [],
            UltimateTattoo: [],
            VietnamFlashbacks: [],
            WorseThanHitler: [],
            worthless: []
        });
    } else {
        console.log(`CanvasManager collection is connected, there are ${await canvasData.size} rows in the database.`);
    }
};